Add appmap models
applandinc/models-js pull request #9
Opened 2020-12-09 23:02 UTC by dustinbyrne

Some areas are still WIP and subject to change. Not worth a review just yet, but the API is likely not to change.

```js
const appmap = buildAppmap()
      .source(await fromFile(file))
      .prune(cmd.size)
      .normalize()
      .build();
```

2020-12-14 18:26 UTC, apotterri approved these changes
LGTM. Probably needs a build job set up soon.

2020-12-14 18:48 UTC, kgilpin requested changes
One probably typo. Also, can you describe the new functionality in the README?

2020-12-14 18:48 UTC, kgilpin commented on src/appmapBuilder.js
> +const BLOCKLISTED_KEYS = new Set(['parent', '_call', '_return']);
BLOCKLISTED or BLACKLISTED?

2020-12-14 23:27 UTC, dustinbyrne commented on src/appmapBuilder.js
> +const BLOCKLISTED_KEYS = new Set(['parent', '_call', '_return']);
"Blocklist" was intended here

2020-12-15 09:37 UTC, sashahonchar approved these changes

2020-12-15 16:39 UTC, dustinbyrne commented
There was some file duplication due to casing changes in file names. I've just fixed it.

2020-12-15 22:03 UTC, merged